apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraudflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraudflow-api
  template:
    metadata:
      labels:
        app: fraudflow-api
    spec:
      containers:
      - name: fraudflow-api
        image: rahulrajparida/fraudflow-api:2f2a9c0dd6ec1d30678787032faa8b658c6f9efc
        imagePullPolicy: Always   
        ports:
        - containerPort: 8000

