apiVersion: v1
kind: Service
metadata:
  name: fraudflow-service
spec:
  type: NodePort
  selector:
    app: fraudflow-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
      